# Generated by Django 4.2.4 on 2023-08-19 17:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('asset_name', models.CharField(max_length=50, null=True)),
                ('asset_abbr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Enter your first name', max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter your last name', max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('phone_number', models.CharField(help_text='Enter your State or Phone Number', max_length=12, null=True)),
                ('reference', models.CharField(default='DPlzeis5XB', editable=False, max_length=10, null=True, unique=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('address', models.CharField(blank=True, help_text='Enter your House address', max_length=500, null=True)),
                ('country', models.CharField(blank=True, help_text='Enter your Country (e.g. Nigeria)', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='kq8sHkLomQ', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('current_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Profit Balance', max_length=100, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_user', to='crypto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_user', to='crypto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_user', to='crypto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MainAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user', to='crypto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='gN4J8oHPiv', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('current_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Account Balance', max_length=100, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invest_user', to='crypto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='lnibYcFCpy', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('minimum_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Completed', max_length=100, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_user', to='crypto.profile')),
            ],
        ),
    ]
