# Generated by Django 4.2.4 on 2023-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_deposit_reference_alter_investment_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='date_initiated',
            new_name='date_requested',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='current_profit',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='roi',
        ),
        migrations.AddField(
            model_name='investment',
            name='account',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Account Balance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Profit Balance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='OpO7AURIWp', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='5iTzutWEi5', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Completed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='FIJJbiLMAD', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='7oJ55oEXq0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Completed', max_length=100, null=True),
        ),
    ]
