# Generated by Django 4.2.4 on 2023-08-20 14:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_deposit_asset_withdrawal_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('site_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_deposit', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='minimum_deposit',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='jlaIDhZF58', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='36t8DhdNiG', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='3P8NzZZgLZ', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='8XOIjO7Mgm', max_length=50, null=True),
        ),
    ]
