# Generated by Django 4.2.4 on 2023-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_alter_deposit_reference_alter_investment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsettings',
            name='company_wallet_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transactionsettings',
            name='starting_account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='ZHobGNt715', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='BcOqaKbhzt', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='2hhwFkbYqZ', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='cIczneVcpC', max_length=50, null=True),
        ),
    ]
