# Generated by Django 4.2.4 on 2023-08-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_alter_deposit_reference_alter_investment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='current_profit',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='roi',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='pQ08DxUvPM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='tj0dNrCQ7K', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='UJGZ3wMcLw', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profitaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='referralaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='CClgvUsYpH', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('current_no_of_return', models.IntegerField(null=True)),
                ('no_of_return', models.IntegerField(null=True)),
                ('profit_per_return', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.packagetype')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.package'),
        ),
    ]
