# Generated by Django 4.2.4 on 2023-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_packagetype_remove_investment_current_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='transactionsettings',
            options={'verbose_name_plural': 'Transaction Settings'},
        ),
        migrations.AddField(
            model_name='package',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='ED4HCh6yDq', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='28ZBuXRiSn', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='4SwtRG0U1p', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='xctBZAJISK', max_length=50, null=True),
        ),
    ]
