# Generated by Django 4.2.4 on 2023-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='Ucq6V4e6EF', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='nEZ6xm4EhD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='ckoZcOR2Is', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='DSam0jVkSz', max_length=50, null=True),
        ),
    ]
