# Generated by Django 4.2.4 on 2023-08-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_alter_deposit_reference_alter_investment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='u9fOOjb8e9', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(default='cLCtxmgiCz', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='hqpHuEo1cC', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='xvfvO57yf9', max_length=50, null=True),
        ),
    ]
